<a href="https://colab.research.google.com/github/85jahnavi/MachineLearning_Assignments/blob/main/NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Arithmetic Operations

**This task involves performing element_wise arithmetic operations on NumPy arrays,It allows addition,subraction,etc..,without requiring explicit loops.**

In [ ]:
import numpy as np
#rank 1
arr1=np.array([1,2,3,4,5])
arr2=np.array([5,4,3,2,1])
'''print(arr1)
print(arr2)'''
sum=arr1+arr2
difference=arr1-arr2
product=arr1*arr2
quotient=arr1/arr2
#Element wise arithmetic operations
print(f"Sum of one dimensional arrays is {sum}")
print(f"Difference of 1D arrays: {difference}")
print(f"Product of 1D arrays is {product}")
print(f"Division of 1D arrays {quotient}")
print("+++++++++++++++++++++++++++++++++++++++++++")
#rank2
arr3=np.array([[1,2,3],[4,5,6]])
arr4=np.array([[7,8,9],[10,11,12]])
sum2=arr3+arr4
difference2=arr3-arr4
product2=arr3*arr4
quotient2=arr3/arr4
print(f"Sum of two dimensional arrays is \n {sum2}")
print(f"Difference of 2D arrays:\n {difference2}")
print(f"Product of 2D arrays is \n {product2}")
print(f"Division of 2D arrays:\n {quotient2}")

Sum of one dimensional arrays is [6 6 6 6 6]
Difference of 1D arrays: [-4 -2  0  2  4]
Product of 1D arrays is [5 8 9 8 5]
Division of 1D arrays [0.2 0.5 1.  2.  5. ]
+++++++++++++++++++++++++++++++++++++++++++
Sum of two dimensional arrays is 
 [[ 8 10 12]
 [14 16 18]]
Difference of 2D arrays:
 [[-6 -6 -6]
 [-6 -6 -6]]
Product of 2D arrays is 
 [[ 7 16 27]
 [40 55 72]]
Division of 2D arrays:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


## Mean and Standard Deviation

**To compute mean the average value of elements in an array and standard deviation measures dispersion of elements around mean,we import numpy as np and use np.mean() and np.std().**

In [ ]:
import numpy as np
#rank 1
arr=np.array([1,2,3,4,5,6])
mean=np.mean(arr)
std_dev=np.std(arr)
print(f"Mean:{mean}")
print(f"Standard Deviation:{std_dev}")
#rank 2
arr1 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
mean_all = np.mean(arr)  # Mean of all elements
print("Mean of the entire array:", mean_all)
mean_row = np.mean(arr1, axis=1)  # Mean of each row
print("Mean of each row:", mean_row)
mean_col = np.mean(arr1, axis=0)  # Mean of each column
print("Mean of each column:", mean_col)
std_all = np.std(arr)  # Standard deviation of all elements
print("Standard deviation of the entire array:", std_all)
std_row = np.std(arr1, axis=1)  # Standard deviation of each row
print("Standard deviation of each row:", std_row)
std_col = np.std(arr1, axis=0)  # Standard deviation of each column
print("Standard deviation of each column:", std_col)



Mean:3.5
Standard Deviation:1.707825127659933
Mean of the entire array: 3.5
Mean of each row: [2. 5. 8.]
Mean of each column: [4. 5. 6.]
Standard deviation of the entire array: 1.707825127659933
Standard deviation of each row: [0.81649658 0.81649658 0.81649658]
Standard deviation of each column: [2.44948974 2.44948974 2.44948974]


# Creating the NumPy array of integers from 10 to 50 with a step size of 5.

**We use np.arange() function which generates evenly spaced values within a specified interval.**

In [ ]:
import numpy as np
arr=np.arange(10,51,5)
print("Array:\n",arr)

Array: [10 15 20 25 30 35 40 45 50]


# Reshape the array

**The reshape() method used to change shape of data(NumPy array) without altering i.e., total no of elements would be same.**

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr)
print("+++++++++++++++++++++++++++++++")
arr1=arr.reshape(2,4)
print("Reshaped array:\n",arr1)

[1 2 3 4 5 6 7 8]
+++++++++++++++++++++++++++++++
Reshaped array [[1 2 3 4]
 [5 6 7 8]]


# Extract sub-matrix and replace elements in the array.

Array slicing is use to extract specific rows and columns from NumPy array and Logical indexing identifies elements satisfying a condition and modifies them directly.

In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
#To access last two rows and first two columns
sub_matrix=arr[1:,:2]# The colon (:) before 2 means select from the beginning up to, but not including index 2.
print(sub_matrix)
#Replace  all elements greater than 4 with 0
arr[arr>4]=0
print("Modified array:\n",arr)

[[ 5  6]
 [ 9 10]]
Modified array [[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]]


# Create a random NumPy array and compute statistics

In [ ]:
import numpy as np
#create a random array
arr=np.random.rand(4,4)
print("Array is",arr)
#mean of each column
mean=np.mean(arr,axis=0)
max_value=np.max(arr)#Maximum value of entire array
sum=np.sum(arr)#sum of all elements
print(f"Mean of each column: {mean}")
print(f"Maximum value :{max_value}")
print(f"Sum of all elements: {sum}")



Array is [[0.13114905 0.71469474 0.92888863 0.91890353]
 [0.74769689 0.9569582  0.66256613 0.27950163]
 [0.40376769 0.74069437 0.63568392 0.74929739]
 [0.7367485  0.91735246 0.2122091  0.80190171]]
Mean of each column: [0.50484053 0.83242494 0.60983695 0.68740107]
Maximum value :0.9569582043527246
Sum of all elements: 10.538013955671314


# Adding 10 to each element and multiplying the result by 2

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
result=(arr+10)*2
print(result)

[22 24 26 28 30]


## Perform advanced slicing and indexing on a 3D array.


*Creating a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from 1 to 100 *

In [ ]:
import numpy as np
arr=np.random.randint(1,101,size=(3,4,5),dtype=np.int64)
print(arr)
# To Extract the second "layer" (i.e., the second 2D array) in the first dimension.
second_layer=arr[1]
#To Extract the first two rows and the last three columns from each "layer."
sub_arrays=arr[:,:2,-3:]
# Replacing all elements divisible by 3 with -1.
print("Second layer in first dimension is:\n",second_layer)
print("Sub array slicing:\n",sub_arrays)
arr[arr%3==0]=-1
print("Modified Array:\n",arr)


[[[94 11 25 57 43]
  [52  3 45  4 52]
  [74 38 27 79 76]
  [54 72 83 83 79]]

 [[62 49 48 82 82]
  [86 12 91  8 33]
  [85  4 75 58 95]
  [72 22 97  4 11]]

 [[68 92 84 57 75]
  [26  8 37 71 67]
  [80 62 79 45 64]
  [42 49 61 98  7]]]
Second layer in first dimension is:
 [[62 49 48 82 82]
 [86 12 91  8 33]
 [85  4 75 58 95]
 [72 22 97  4 11]]
Sub array slicing:
 [[[25 57 43]
  [45  4 52]]

 [[48 82 82]
  [91  8 33]]

 [[84 57 75]
  [37 71 67]]]
Modified Array:
 [[[94 11 25 -1 43]
  [52 -1 -1  4 52]
  [74 38 -1 79 76]
  [-1 -1 83 83 79]]

 [[62 49 -1 82 82]
  [86 -1 91  8 -1]
  [85  4 -1 58 95]
  [-1 22 97  4 11]]

 [[68 92 -1 -1 -1]
  [26  8 37 71 67]
  [80 62 79 -1 64]
  [-1 49 61 98  7]]]


# Broadcasting and advanced operations in numpy.

**Create a NumPy array arr of shape (3, 3) with random integers between
 1 and 20.**

In [ ]:
import numpy as np
arr=np.random.randint(1,21,(3,3),dtype=np.int64)
print(arr)
#Row-wise Normalisation
row=np.mean(arr,axis=1)
arr=arr-row
print(arr)
square=np.square(arr)
print("New array by squaring all elements is: ",square)
#To Find the indices of the top 3 maximum values in the entire array.


[[11 11  2]
 [16  3  9]
 [16  5 20]]
[[  3.           1.66666667 -11.66666667]
 [  8.          -6.33333333  -4.66666667]
 [  8.          -4.33333333   6.33333333]]
New array by squaring all elements is:  [[  9.           2.77777778 136.11111111]
 [ 64.          40.11111111  21.77777778]
 [ 64.          18.77777778  40.11111111]]
